### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by thalesfsp** [consulthys/logstash-input-rets#1]
Hello @consulthys!

  It's an incredible job! I would like to know if this plugin supports downloading images from the servers. Are you still using/maintaining this?

Thank you!

**Comment by consulthys** [comment]
Hi @thalesfsp, thanks, much appreciated.
I'm still maintaining this, but at the moment it doesn't support photo pulling, mainly because Logstash doesn't handle binary data that well.

However, you may check my other repo (https://github.com/consulthys/rets-client) which provides a full fledged Node.js RETS client with which you can download photos at will.

**Comment by thalesfsp** [comment]
@consulthys Thank you!
